### ISSUE TITLE
Error during game creation

### ISSUE THREAD

**Issue by TheOneJohiah** [gamma-delta/petraspace#12]
This was on game start, all default settings, all need prereq mods enabled (except the optional tinting one)
Is there a more detailed log I can pull from somewhere?

See below:
The mod Petrak@'s Space Mod (0.2.0) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event petraspace::on_init()
__petraspace__/control/misc.lua:13: attempt to index local 'tech' (a nil value)
stack traceback:
	__petraspace__/control/misc.lua:13: in function 'add_qai_techs'
	__petraspace__/control/misc.lua:93: in function 'on_init'
	__core__/lualib/event_handler.lua:69: in function <__core__/lualib/event_handler.lua:64>

**Comment by gamma-delta** [comment]
I fixed this a while ago I think

**Comment by TheOneJohiah** [comment]
Just checked again and I'm still getting it, with only the required mods and the dlc stuff enabled. Is there like a log somewhere  I can get you?
